controller:
  hero_chassis_controller:
    type: hero_chassis_controller/HeroChassisController
    pid_1: { p: 5000.0, i: 100, d: 5.0}
    pid_2: { p: 5000.0, i: 100, d: 5.0}
    pid_3: { p: 5000.0, i: 100, d: 5.0}
    pid_4: { p: 5000.0, i: 100, d: 5.0}
    Wheel_track: 0.400
    Wheel_base: 0.400

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
