controller:
  hero_chassis_controller:
    type: hero_chassis_controller/HeroChassisController
    pid1: { p: 4000.0, i: 0, d: 5.0}
    pid2: { p: 4000.0, i: 0, d: 5.0}
    pid3: { p: 4000.0, i: 0, d: 5.0}
    pid4: { p: 4000.0, i: 0, d: 5.0}
    Wheel_Track: 0.400
    Wheel_Base: 0.400

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50


